[ClassVersion("1.0.0.0"), FriendlyName("xFirewallTcpRule")]
class xFirewallTcpRule : OMI_BaseResource
{
    [Key] String Name;
    [Required] UInt16 Port;
    [Write, ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
};
